/* eslint-disable no-restricted-globals */
// This file is automatically generated by Workbox during the build process.
// It's designed to be minimal and allow Workbox to inject the precache manifest.

import { precacheAndRoute } from 'workbox-precaching';

// This line will be replaced by Workbox with the list of files to precache.
// For example: self.__WB_MANIFEST = [{url: "index.html", revision: "abc"}, ...];
precacheAndRoute(self.__WB_MANIFEST);

// You can add your custom service worker logic here.
// For example, handling push notifications, background sync, etc.

// Example: Cache runtime requests (e.g., API calls)
// import { registerRoute } from 'workbox-routing';
// import { CacheFirst } from 'workbox-strategies';
// import { CacheableResponsePlugin } from 'workbox-cacheable-response';

// registerRoute(
//   ({ url }) => url.origin === 'https://api.example.com', // Replace with your API origin
//   new CacheFirst({
//     cacheName: 'api-cache',
//     plugins: [
//       new CacheableResponsePlugin({
//         statuses: [0, 200], // Cache opaque responses and successful ones
//       }),
//     ],
//   })
// );
